### PR TITLE
Upgrade DockerFile configuration

### PR DESCRIPTION
**Pull request by thomas-illiet**
https://github.com/angristan/feedbin-docker/issues/58

### CODE REVIEW

**Comment by angristan** [comment]
👋 Thanks! Can you confirm the services are working fine with these versions?

**Comment by angristan** [comment]
Fuck, I did it again 😔

**Comment by angristan** [comment]
I wasn't able to force push to your branch *after* messing everything up, somehow. I still had the commits locally so I merged your changes in #60.

Sorry, and thanks!

**Comment by thomas-illiet** [comment]
it is not a problem for me, the goal is to participate in the project :)

**Pull request closed without merging**
