### PR TITLE
WIP: Reuse some ENV variables and create Minio bucket automatically

### PR DESCRIPTION
**Pull request by karlprieb**
This PR aim to make the `.env` file more simple and to avoid repeating the same values for more than one ENV.
Other change is that now you don't need to manually create the minio bucket

I still need to update the README.

### CODE REVIEW

**Comment by gotmax23** [comment]
In your .env file, the `ELASTICSEARCH_URL` and `MEMCACHED_HOSTS` hostnames don't correspond to those in the docker-compose file. They should be:
ELASTICSEARCH_URL=http://**feedbin-**elasticsearch:9200
MEMCACHED_HOSTS=**feedbin-**memcached:11211Se

Your PR would overwrite #47, where this was fixed.

**Comment by karlprieb** [comment]
Thank you for pointing this out @gotmax23 
I totally forgot to finish this PR.
In fact I'm having some issues with the bucket permissions... maybe I'll just open a PR reusing the `MINIO` env variables on `AWS` ones to shrink the `.env` file a little bit and after that I'll take a look on this bucket permission issue that I'm having.

**Comment by gotmax23** [comment]
@karlprieb Maybe try not setting any permissions at all. I set up my minio bucket that way and it seemed to work fine. Also, there was the same issues with the hostnames in the Caddyfile.example.

**Comment by karlprieb** [comment]
@gotmax23 yep... I just tried to make this automatically, but idk if worth the effort... you have to change the permission only one time anyway

**Pull request closed without merging**
